In [9]:
import torch
import numpy as np

# data_ = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/build/center.bin', dtype=np.float32).reshape([1, 2, 200, 176])
# print(data_)

data_from_c = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/build/feature_.bin', dtype=np.float32).reshape([1, 256, 200, 176])
data_from_python = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/src/spatial_features.bin', dtype=np.float32).reshape([1, 256, 200, 176])

print(sum(sum(sum(data_from_c))))
print(sum(sum(sum(data_from_python))))


[1677.5482   1596.4854   2031.6742   2385.5269   3624.7542   5170.1367
 5441.1665   6292.1885   6686.363    5936.925    4841.1743   5469.4883
 7031.234    6722.957    6715.4077   5435.8364   3868.2256   3214.021
 3477.7686   4158.9194   4316.4697   3410.1704   3524.8252   2950.5283
 3890.5645   4686.0356   4947.08     4715.41     4264.336    3882.4854
 3352.684    3542.1416   3984.2495   3463.601    2973.9985   2873.2266
 3442.8071   3302.7744   3362.5928   3465.3638   3051.8933   2856.8447
 3604.4243   4544.2476   4419.2256   3669.8708   3261.2522   3767.9402
 3634.2568   2840.5923   2453.4685   2567.0105   2485.478    2897.4917
 3042.7935   3082.625    3141.125    3019.96     4140.6445   4031.8394
 3094.355    2561.524    3031.8755   2692.7437   2199.239    1838.6655
 2016.6727   1217.1394   1031.1726   1478.4729   1817.95     2054.211
 1970.8136   1930.4857   1621.271    1621.9429   1480.1145   1479.6531
 1565.5743   1423.7935   1258.6096   1126.3418   1195.7031   1154.531
 1109.101

In [29]:
data_from_c = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/src/voxel_coords.bin', dtype=np.float32).reshape([36368, 4])
print(data_from_c)

[[  0.  37. 907. 309.]
 [  0.  37. 908. 309.]
 [  0.  38. 947. 373.]
 ...
 [  0.  12. 770.  74.]
 [  0.  12. 771.  74.]
 [  0.  13. 772.  72.]]


In [10]:
voxels2 = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/src/voxel_features.bin', dtype=np.float16).reshape([36368, 4])
coors2 = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/src/voxel_coords.bin', dtype=np.float32).reshape([36368, 4])
print(voxels2)
print(coors2)

[[15.45   5.387  0.762  0.57 ]
 [15.47   5.45   0.764  0.48 ]
 [18.66   7.38   0.887  0.13 ]
 ...
 [ 3.709 -1.47  -1.744  0.33 ]
 [ 3.723 -1.426 -1.743  0.346]
 [ 3.633 -1.354 -1.692  0.   ]]
[[  0.  37. 907. 309.]
 [  0.  37. 908. 309.]
 [  0.  38. 947. 373.]
 ...
 [  0.  12. 770.  74.]
 [  0.  12. 771.  74.]
 [  0.  13. 772.  72.]]


In [32]:
data_ = np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/voxel_features.bin', dtype=np.float16)
data_ = data_.astype(np.float32)
print(data_)
data_.tofile('voxel_features2.bin')
print(data_)

[15.453125    5.3867188   0.76220703 ... -1.3535156  -1.6923828
  0.        ]
[15.453125    5.3867188   0.76220703 ... -1.3535156  -1.6923828
  0.        ]


In [31]:
np.fromfile('/root/autodl-tmp/code/Lidar_AI_Solution/CUDA-CenterPoint/voxel_features2.bin', dtype=np.float32)

array([15.453125  ,  5.3867188 ,  0.76220703, ..., -1.3535156 ,
       -1.6923828 ,  0.        ], dtype=float32)